// <autogenerated>
//   This file was generated using ITransferOrderDetailServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Inventory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Inventory
{
    public interface ITransferOrderDetailServices : IServices
    {
        bool InsertTransferOrderDetail(TransferOrderDetailModel TransferOrderDetailModel);
		IQueryable<TransferOrderDetailModel> GetTransferOrderDetails();
        Task<TransferOrderDetailModel> GetTransferOrderDetailById(int TransferOrderDetailId);
        Task UpdateTransferOrderDetail(TransferOrderDetailModel TransferOrderDetail);
        Task DeleteTransferOrderDetail(int TransferOrderDetailId);
    }
}
