// <autogenerated>
//   This file was generated using IPayrollRecordServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Payroll;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Payroll
{
    public interface IPayrollRecordServices : IServices
    {
        bool InsertPayrollRecord(PayrollRecordModel PayrollRecordModel);
		IQueryable<PayrollRecordModel> GetPayrollRecords();
        Task<PayrollRecordModel> GetPayrollRecordById(int PayrollRecordId);
        Task UpdatePayrollRecord(PayrollRecordModel PayrollRecord);
        Task DeletePayrollRecord(int PayrollRecordId);
    }
}
