// <autogenerated>
//   This file was generated using IPayrollProfileServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Payroll;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Payroll
{
    public interface IPayrollProfileServices : IServices
    {
        bool InsertPayrollProfile(PayrollProfileModel PayrollProfileModel);
		IQueryable<PayrollProfileModel> GetPayrollProfiles();
        Task<PayrollProfileModel> GetPayrollProfileById(int PayrollProfileId);
        Task UpdatePayrollProfile(PayrollProfileModel PayrollProfile);
        Task DeletePayrollProfile(int PayrollProfileId);
    }
}
