// <autogenerated>
//   This file was generated using IStaffPayrollRecordServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Payroll;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Payroll
{
    public interface IStaffPayrollRecordServices : IServices
    {
        bool InsertStaffPayrollRecord(StaffPayrollRecordModel StaffPayrollRecordModel);
		IQueryable<StaffPayrollRecordModel> GetStaffPayrollRecords();
        Task<StaffPayrollRecordModel> GetStaffPayrollRecordById(int StaffPayrollRecordId);
        Task UpdateStaffPayrollRecord(StaffPayrollRecordModel StaffPayrollRecord);
        Task DeleteStaffPayrollRecord(int StaffPayrollRecordId);
    }
}
