// <autogenerated>
//   This file was generated using IConfigPositionTypeServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Config;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Config
{
    public interface IConfigPositionTypeServices : IServices
    {
        bool InsertConfigPositionType(ConfigPositionTypeModel ConfigPositionTypeModel);
		IQueryable<ConfigPositionTypeModel> GetConfigPositionTypes();
        Task<ConfigPositionTypeModel> GetConfigPositionTypeById(int ConfigPositionTypeId);
        Task UpdateConfigPositionType(ConfigPositionTypeModel ConfigPositionType);
        Task DeleteConfigPositionType(int ConfigPositionTypeId);
    }
}
