// <autogenerated>
//   This file was generated using IConfigVisaTypeServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Config;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Config
{
    public interface IConfigVisaTypeServices : IServices
    {
        bool InsertConfigVisaType(ConfigVisaTypeModel ConfigVisaTypeModel);
		IQueryable<ConfigVisaTypeModel> GetConfigVisaTypes();
        Task<ConfigVisaTypeModel> GetConfigVisaTypeById(int ConfigVisaTypeId);
        Task UpdateConfigVisaType(ConfigVisaTypeModel ConfigVisaType);
        Task DeleteConfigVisaType(int ConfigVisaTypeId);
    }
}
