// <autogenerated>
//   This file was generated using IConfigLeaveServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Config;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Config
{
    public interface IConfigLeaveServices : IServices
    {
        bool InsertConfigLeave(ConfigLeaveModel ConfigLeaveModel);
		IQueryable<ConfigLeaveModel> GetConfigLeaves();
        Task<ConfigLeaveModel> GetConfigLeaveById(int ConfigLeaveId);
        Task UpdateConfigLeave(ConfigLeaveModel ConfigLeave);
        Task DeleteConfigLeave(int ConfigLeaveId);
    }
}
