// <autogenerated>
//   This file was generated using IConfigPayCodeValueServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Config;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Config
{
    public interface IConfigPayCodeValueServices : IServices
    {
        bool InsertConfigPayCodeValue(ConfigPayCodeValueModel ConfigPayCodeValueModel);
		IQueryable<ConfigPayCodeValueModel> GetConfigPayCodeValues();
        Task<ConfigPayCodeValueModel> GetConfigPayCodeValueById(int ConfigPayCodeValueId);
        Task UpdateConfigPayCodeValue(ConfigPayCodeValueModel ConfigPayCodeValue);
        Task DeleteConfigPayCodeValue(int ConfigPayCodeValueId);
    }
}
