// <autogenerated>
//   This file was generated using IConfigBankServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Config;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Config
{
    public interface IConfigBankServices : IServices
    {
        bool InsertConfigBank(ConfigBankModel ConfigBankModel);
		IQueryable<ConfigBankModel> GetConfigBanks();
        Task<ConfigBankModel> GetConfigBankById(int ConfigBankId);
        Task UpdateConfigBank(ConfigBankModel ConfigBank);
        Task DeleteConfigBank(int ConfigBankId);
    }
}
