// <autogenerated>
//   This file was generated using IConfigShiftTypeServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Config;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Config
{
    public interface IConfigShiftTypeServices : IServices
    {
        bool InsertConfigShiftType(ConfigShiftTypeModel ConfigShiftTypeModel);
		IQueryable<ConfigShiftTypeModel> GetConfigShiftTypes();
        Task<ConfigShiftTypeModel> GetConfigShiftTypeById(int ConfigShiftTypeId);
        Task UpdateConfigShiftType(ConfigShiftTypeModel ConfigShiftType);
        Task DeleteConfigShiftType(int ConfigShiftTypeId);
    }
}
