// <autogenerated>
//   This file was generated using IConfigShiftTypeRepository.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>
using CBMS.Models;
using CBMS.Models.Config;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace CBMS.Repositories.Interfaces.Config
{
    public interface IConfigShiftTypeRepository : IRepository<ConfigShiftTypeModel>,IDisposable
    {
	    /// <summary>
        /// Insert the ConfigShiftType Model into Database
        /// </summary>
        /// <param name="ConfigShiftType"></param>
        #region Create
        void InsertConfigShiftType(ConfigShiftTypeModel ConfigShiftType);
        #endregion

        #region Read
        /// <summary>
        /// Get All Active ConfigShiftTypes
        /// </summary>
        /// <returns></returns>
        IQueryable<ConfigShiftTypeModel> GetConfigShiftTypes();
        /// <summary>
        /// Get All Active ConfigShiftTypes as Enumerable (Forced loading)
        /// </summary>
        /// <returns></returns>
        IEnumerable<ConfigShiftTypeModel> GetConfigShiftTypesAsList();
        /// <summary>
        /// Get ConfigShiftType using its Id.
        /// </summary>
        /// <param name="ConfigShiftTypeId"></param>
        /// <returns></returns>
        ConfigShiftTypeModel GetConfigShiftTypeById(int ConfigShiftTypeId);

        /// <summary>
        /// Get ConfigShiftType using its Id. (Async)
        /// </summary>
        /// <param name="ConfigShiftTypeId"></param>
        /// <returns></returns>
        Task<ConfigShiftTypeModel> GetConfigShiftTypeByIdAsync(int ConfigShiftTypeId);
        #endregion

        #region Update
        /// <summary>
        /// Update ConfigShiftType Model.
        /// </summary>
        /// <param name="ConfigShiftType"></param>
        void UpdateConfigShiftType(ConfigShiftTypeModel ConfigShiftType);
        /// <summary>
        /// Update ConfigShiftType Model (Async)
        /// </summary>
        /// <param name="ConfigShiftType"></param>
        /// <returns></returns>
        Task UpdateConfigShiftTypeAsync(ConfigShiftTypeModel ConfigShiftType);
        #endregion

        #region Delete
        /// <summary>
        /// Mark the ConfigShiftType Model as Deleted in DB.
        /// </summary>
        /// <param name="ConfigShiftTypeId"></param>
        void DeleteConfigShiftType(int ConfigShiftTypeId);
        /// <summary>
        /// Mark the ConfigShiftType Model as Deleted in DB. (Async)
        /// </summary>
        /// <param name="ConfigShiftTypeId"></param>
        /// <returns></returns>
        Task DeleteConfigShiftTypeAsync(int ConfigShiftTypeId);
        #endregion
    }
}