// <autogenerated>
//   This file was generated using IOutletServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Roster
{
    public interface IOutletServices : IServices
    {
        OutletModel InsertOutlet(OutletModel OutletModel);
        IQueryable<OutletModel> GetOutlets();
        Task<OutletModel> GetOutletById(int OutletId);
        Task UpdateOutlet(OutletModel Outlet);
        Task DeleteOutlet(int OutletId);

        OutletModel AssignOutletToBrand(OutletModel outlet, BrandModel brand);
        OutletModel RelocateOutlet(OutletModel outlet, BrandModel brand);
        LocationModel EditLocation(LocationModel location);

        OutletModel InsertDepartment(OutletModel outlet, DepartmentModel department);
        DepartmentModel GetDepartmentById(int deptId);
        List<DepartmentModel> GetDepartments(OutletModel outlet);
        DepartmentModel EditDepartment(DepartmentModel department);
        DepartmentModel DeleteDepartment(DepartmentModel department);
        DepartmentModel RelocateDepartment(DepartmentModel department, OutletModel outlet);

        List<PositionModel> GetPositions(DepartmentModel department);

        List<StaffProfileModel> GetStaffProfiles(DepartmentModel department);
        List<StaffProfileModel> GetStaffProfiles(OutletModel outlet);

        /// <summary>
        /// Copy all departments under the same outlet to target outlet
        /// </summary>
        /// <param name="outlet">outlet to copy from</param>
        /// <returns>Outlet with department configurations</returns>
        OutletModel CopyOutletConfigure(OutletModel srcOutlet,OutletModel dstOutlet);

        /// <summary>
        /// Clone all position configure under the department to a new department
        /// </summary>
        /// <param name="department">source department</param>
        /// <returns>department with same configurations</returns>
        DepartmentModel CopyDepartmentConfigure(DepartmentModel srcDepartment, DepartmentModel dstDepartment);
    }
}
