// <autogenerated>
//   This file was generated using IPositionServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Config;
using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Roster
{
    public interface IPositionServices : IServices
    {
        PositionModel InsertPosition(PositionModel PositionModel);
        PositionModel InsertPosition(PositionModel PositionModel, OutletModel outlet);
        PositionModel InsertPosition(PositionModel PositionModel, DepartmentModel department);
        List<PositionModel> GetPositions();
        List<PositionModel> GetPositions(OutletModel outlet);
        List<PositionModel> GetPositions(DepartmentModel department);
        Task<PositionModel> GetPositionById(int PositionId);
        PositionModel UpdatePosition(PositionModel Position);
        PositionModel DeletePosition(PositionModel Position);
        PositionModel DeletePosition(PositionModel Position, OutletModel outlet);
        PositionModel DeletePosition(PositionModel Position, DepartmentModel department);

        List<ConfigPayCodeValueModel> GetPayCodes(PositionModel Position);

        ConfigPayCodeValueModel AddPayCodeToPosition(ConfigPayCodeValueModel paycode, PositionModel position);
        ConfigPayCodeValueModel RemovePayCodeFromPosition(ConfigPayCodeValueModel paycode, PositionModel position);
        List<PositionModel> CopyPayCodeForPositions(PositionModel position);

        List<ConfigLeaveModel> GetLeaveTypeForPosition(PositionModel position);
        ConfigLeaveModel AddLeaveToPosition(ConfigLeaveModel ConfigLeave, PositionModel position);
        ConfigLeaveModel RemoveLeaveFromPosition(ConfigLeaveModel ConfigLeave, PositionModel position);

    }
}
