// <autogenerated>
//   This file was generated using IStaffProfilePaymentDetailServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Roster
{
    public interface IStaffProfilePaymentDetailServices : IServices
    {
        bool InsertStaffProfilePaymentDetail(StaffProfilePaymentDetailModel StaffProfilePaymentDetailModel);
		IQueryable<StaffProfilePaymentDetailModel> GetStaffProfilePaymentDetails();
        Task<StaffProfilePaymentDetailModel> GetStaffProfilePaymentDetailById(int StaffProfilePaymentDetailId);
        Task UpdateStaffProfilePaymentDetail(StaffProfilePaymentDetailModel StaffProfilePaymentDetail);
        Task DeleteStaffProfilePaymentDetail(int StaffProfilePaymentDetailId);
    }
}
