// <autogenerated>
//   This file was generated using IStaffProfileLeaveProfileServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Roster
{
    public interface IStaffProfileLeaveProfileServices : IServices
    {
        bool InsertStaffProfileLeaveProfile(StaffProfileLeaveProfileModel StaffProfileLeaveProfileModel);
		IQueryable<StaffProfileLeaveProfileModel> GetStaffProfileLeaveProfiles();
        Task<StaffProfileLeaveProfileModel> GetStaffProfileLeaveProfileById(int StaffProfileLeaveProfileId);
        Task UpdateStaffProfileLeaveProfile(StaffProfileLeaveProfileModel StaffProfileLeaveProfile);
        Task DeleteStaffProfileLeaveProfile(int StaffProfileLeaveProfileId);
    }
}
