// <autogenerated>
//   This file was generated using IStaffProfileServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Roster
{
    public interface IStaffProfileServices : IServices
    {
        bool InsertStaffProfile(StaffProfileModel StaffProfileModel);
		IQueryable<StaffProfileModel> GetStaffProfiles();
        Task<StaffProfileModel> GetStaffProfileById(int StaffProfileId);
        Task UpdateStaffProfile(StaffProfileModel StaffProfile);
        Task DeleteStaffProfile(int StaffProfileId);
    }
}
