// <autogenerated>
//   This file was generated using IStaffInfoJobHistoryServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Roster
{
    public interface IStaffInfoJobHistoryServices : IServices
    {
        bool InsertStaffInfoJobHistory(StaffInfoJobHistoryModel StaffInfoJobHistoryModel);
		IQueryable<StaffInfoJobHistoryModel> GetStaffInfoJobHistories();
        Task<StaffInfoJobHistoryModel> GetStaffInfoJobHistoryById(int StaffInfoJobHistoryId);
        Task UpdateStaffInfoJobHistory(StaffInfoJobHistoryModel StaffInfoJobHistory);
        Task DeleteStaffInfoJobHistory(int StaffInfoJobHistoryId);
    }
}
