// <autogenerated>
//   This file was generated using IStaffInfoVisaServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Roster
{
    public interface IStaffInfoVisaServices : IServices
    {
        bool InsertStaffInfoVisa(StaffInfoVisaModel StaffInfoVisaModel);
		IQueryable<StaffInfoVisaModel> GetStaffInfoVisas();
        Task<StaffInfoVisaModel> GetStaffInfoVisaById(int StaffInfoVisaId);
        Task UpdateStaffInfoVisa(StaffInfoVisaModel StaffInfoVisa);
        Task DeleteStaffInfoVisa(int StaffInfoVisaId);
    }
}
