// <autogenerated>
//   This file was generated using IStaffInfoServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Roster
{
    public interface IStaffInfoServices : IServices
    {
        bool InsertStaffInfo(StaffInfoModel StaffInfoModel);
		IQueryable<StaffInfoModel> GetStaffInfoes();
        Task<StaffInfoModel> GetStaffInfoById(int StaffInfoId);
        Task UpdateStaffInfo(StaffInfoModel StaffInfo);
        Task DeleteStaffInfo(int StaffInfoId);
    }
}
