// <autogenerated>
//   This file was generated using IStaffInfoContactServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.Services.Interfaces.Roster
{
    public interface IStaffInfoContactServices : IServices
    {
        bool InsertStaffInfoContact(StaffInfoContactModel StaffInfoContactModel);
		IQueryable<StaffInfoContactModel> GetStaffInfoContacts();
        Task<StaffInfoContactModel> GetStaffInfoContactById(int StaffInfoContactId);
        Task UpdateStaffInfoContact(StaffInfoContactModel StaffInfoContact);
        Task DeleteStaffInfoContact(int StaffInfoContactId);
    }
}
