// <autogenerated>
//   This file was generated using PayrollProfileServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Payroll;
using CBMS.Services.Interfaces.Payroll;
using CBMS.Repositories.Interfaces.Payroll;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CBMS.Models;
using System.Web.Configuration;

namespace CBMS.Services.Payroll
{
    public class PayrollProfileServices : CBMSServices,IPayrollProfileServices
    {
		private string PayrollProfileRepositoryName = WebConfigurationManager.AppSettings["CBMS.REPOSITORIES.PAYROLL.PAYROLLPROFILE"];
	
        private IPayrollProfileRepository _PayrollProfileRepository;
		
        public PayrollProfileServices(ModelStateDictionary modelStateDictionary)
        {
            this._modelStateDictionary = modelStateDictionary;
			this.dbContext = new CBMSDbContext();
            this._PayrollProfileRepository = (IPayrollProfileRepository)Activator.CreateInstance(Type.GetType(PayrollProfileRepositoryName), dbContext);
        }
		public PayrollProfileServices(ModelStateDictionary modelStateDictionary,CBMSDbContext dbContext)
        {
            this._modelStateDictionary = modelStateDictionary;
			this.dbContext = dbContext;
            this._PayrollProfileRepository = (IPayrollProfileRepository)Activator.CreateInstance(Type.GetType(PayrollProfileRepositoryName), dbContext);
        }
		
        public bool InsertPayrollProfile(PayrollProfileModel PayrollProfileModel)
        {
            // should have some validation here...

            // Finally put to repository
            try
            {
                _PayrollProfileRepository.Create(PayrollProfileModel);
                return true;
            }
            catch (Exception e)
            {
                _modelStateDictionary.AddModelError("Insert Exception", e.Message);
                return false;
            }
        }

		public IQueryable<PayrollProfileModel> GetPayrollProfiles(){
			return this._PayrollProfileRepository.GetPayrollProfiles();
		}
		
        public async Task<PayrollProfileModel> GetPayrollProfileById(int PayrollProfileId)
        {
            return await this._PayrollProfileRepository.GetPayrollProfileByIdAsync(PayrollProfileId);
        }

        public async Task UpdatePayrollProfile(PayrollProfileModel PayrollProfile)
        {
            await this._PayrollProfileRepository.UpdatePayrollProfileAsync(PayrollProfile);
        }

        public async Task DeletePayrollProfile(int PayrollProfileId)
        {
            await this._PayrollProfileRepository.DeletePayrollProfileAsync(PayrollProfileId);
        }
		
    }
}