// <autogenerated>
//   This file was generated using StaffPayrollRecordServices.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>

using CBMS.Models.Payroll;
using CBMS.Services.Interfaces.Payroll;
using CBMS.Repositories.Interfaces.Payroll;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CBMS.Models;
using System.Web.Configuration;

namespace CBMS.Services.Payroll
{
    public class StaffPayrollRecordServices : CBMSServices,IStaffPayrollRecordServices
    {
		private string StaffPayrollRecordRepositoryName = WebConfigurationManager.AppSettings["CBMS.REPOSITORIES.PAYROLL.STAFFPAYROLLRECORD"];
	
        private IStaffPayrollRecordRepository _StaffPayrollRecordRepository;
		
        public StaffPayrollRecordServices(ModelStateDictionary modelStateDictionary)
        {
            this._modelStateDictionary = modelStateDictionary;
			this.dbContext = new CBMSDbContext();
            this._StaffPayrollRecordRepository = (IStaffPayrollRecordRepository)Activator.CreateInstance(Type.GetType(StaffPayrollRecordRepositoryName), dbContext);
        }
		public StaffPayrollRecordServices(ModelStateDictionary modelStateDictionary,CBMSDbContext dbContext)
        {
            this._modelStateDictionary = modelStateDictionary;
			this.dbContext = dbContext;
            this._StaffPayrollRecordRepository = (IStaffPayrollRecordRepository)Activator.CreateInstance(Type.GetType(StaffPayrollRecordRepositoryName), dbContext);
        }
		
        public bool InsertStaffPayrollRecord(StaffPayrollRecordModel StaffPayrollRecordModel)
        {
            // should have some validation here...

            // Finally put to repository
            try
            {
                _StaffPayrollRecordRepository.Create(StaffPayrollRecordModel);
                return true;
            }
            catch (Exception e)
            {
                _modelStateDictionary.AddModelError("Insert Exception", e.Message);
                return false;
            }
        }

		public IQueryable<StaffPayrollRecordModel> GetStaffPayrollRecords(){
			return this._StaffPayrollRecordRepository.GetStaffPayrollRecords();
		}
		
        public async Task<StaffPayrollRecordModel> GetStaffPayrollRecordById(int StaffPayrollRecordId)
        {
            return await this._StaffPayrollRecordRepository.GetStaffPayrollRecordByIdAsync(StaffPayrollRecordId);
        }

        public async Task UpdateStaffPayrollRecord(StaffPayrollRecordModel StaffPayrollRecord)
        {
            await this._StaffPayrollRecordRepository.UpdateStaffPayrollRecordAsync(StaffPayrollRecord);
        }

        public async Task DeleteStaffPayrollRecord(int StaffPayrollRecordId)
        {
            await this._StaffPayrollRecordRepository.DeleteStaffPayrollRecordAsync(StaffPayrollRecordId);
        }
		
    }
}