// <autogenerated>
//   This file was generated using IStaffProfileAdminStatusRepository.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>
using CBMS.Models;
using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace CBMS.Repositories.Interfaces.Roster
{
    public interface IStaffProfileAdminStatusRepository : IRepository<StaffProfileAdminStatusModel>,IDisposable
    {
	    /// <summary>
        /// Insert the StaffProfileAdminStatus Model into Database
        /// </summary>
        /// <param name="StaffProfileAdminStatus"></param>
        #region Create
        void InsertStaffProfileAdminStatus(StaffProfileAdminStatusModel StaffProfileAdminStatus);
        #endregion

        #region Read
        /// <summary>
        /// Get All Active StaffProfileAdminStatuss
        /// </summary>
        /// <returns></returns>
        IQueryable<StaffProfileAdminStatusModel> GetStaffProfileAdminStatus();
        /// <summary>
        /// Get All Active StaffProfileAdminStatus as Enumerable (Forced loading)
        /// </summary>
        /// <returns></returns>
        IEnumerable<StaffProfileAdminStatusModel> GetStaffProfileAdminStatusAsList();
        /// <summary>
        /// Get StaffProfileAdminStatus using its Id.
        /// </summary>
        /// <param name="StaffProfileAdminStatusId"></param>
        /// <returns></returns>
        StaffProfileAdminStatusModel GetStaffProfileAdminStatusById(int StaffProfileAdminStatusId);

        /// <summary>
        /// Get StaffProfileAdminStatus using its Id. (Async)
        /// </summary>
        /// <param name="StaffProfileAdminStatusId"></param>
        /// <returns></returns>
        Task<StaffProfileAdminStatusModel> GetStaffProfileAdminStatusByIdAsync(int StaffProfileAdminStatusId);
        #endregion

        #region Update
        /// <summary>
        /// Update StaffProfileAdminStatus Model.
        /// </summary>
        /// <param name="StaffProfileAdminStatus"></param>
        void UpdateStaffProfileAdminStatus(StaffProfileAdminStatusModel StaffProfileAdminStatus);
        /// <summary>
        /// Update StaffProfileAdminStatus Model (Async)
        /// </summary>
        /// <param name="StaffProfileAdminStatus"></param>
        /// <returns></returns>
        Task UpdateStaffProfileAdminStatusAsync(StaffProfileAdminStatusModel StaffProfileAdminStatus);
        #endregion

        #region Delete
        /// <summary>
        /// Mark the StaffProfileAdminStatus Model as Deleted in DB.
        /// </summary>
        /// <param name="StaffProfileAdminStatusId"></param>
        void DeleteStaffProfileAdminStatus(int StaffProfileAdminStatusId);
        /// <summary>
        /// Mark the StaffProfileAdminStatus Model as Deleted in DB. (Async)
        /// </summary>
        /// <param name="StaffProfileAdminStatusId"></param>
        /// <returns></returns>
        Task DeleteStaffProfileAdminStatusAsync(int StaffProfileAdminStatusId);
        #endregion
    }
}