// <autogenerated>
//   This file was generated using IStaffProfileLeaveRecordRepository.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>
using CBMS.Models;
using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace CBMS.Repositories.Interfaces.Roster
{
    public interface IStaffProfileLeaveRecordRepository : IRepository<StaffProfileLeaveRecordModel>,IDisposable
    {
	    /// <summary>
        /// Insert the StaffProfileLeaveRecord Model into Database
        /// </summary>
        /// <param name="StaffProfileLeaveRecord"></param>
        #region Create
        void InsertStaffProfileLeaveRecord(StaffProfileLeaveRecordModel StaffProfileLeaveRecord);
        #endregion

        #region Read
        /// <summary>
        /// Get All Active StaffProfileLeaveRecords
        /// </summary>
        /// <returns></returns>
        IQueryable<StaffProfileLeaveRecordModel> GetStaffProfileLeaveRecords();
        /// <summary>
        /// Get All Active StaffProfileLeaveRecords as Enumerable (Forced loading)
        /// </summary>
        /// <returns></returns>
        IEnumerable<StaffProfileLeaveRecordModel> GetStaffProfileLeaveRecordsAsList();
        /// <summary>
        /// Get StaffProfileLeaveRecord using its Id.
        /// </summary>
        /// <param name="StaffProfileLeaveRecordId"></param>
        /// <returns></returns>
        StaffProfileLeaveRecordModel GetStaffProfileLeaveRecordById(int StaffProfileLeaveRecordId);

        /// <summary>
        /// Get StaffProfileLeaveRecord using its Id. (Async)
        /// </summary>
        /// <param name="StaffProfileLeaveRecordId"></param>
        /// <returns></returns>
        Task<StaffProfileLeaveRecordModel> GetStaffProfileLeaveRecordByIdAsync(int StaffProfileLeaveRecordId);
        #endregion

        #region Update
        /// <summary>
        /// Update StaffProfileLeaveRecord Model.
        /// </summary>
        /// <param name="StaffProfileLeaveRecord"></param>
        void UpdateStaffProfileLeaveRecord(StaffProfileLeaveRecordModel StaffProfileLeaveRecord);
        /// <summary>
        /// Update StaffProfileLeaveRecord Model (Async)
        /// </summary>
        /// <param name="StaffProfileLeaveRecord"></param>
        /// <returns></returns>
        Task UpdateStaffProfileLeaveRecordAsync(StaffProfileLeaveRecordModel StaffProfileLeaveRecord);
        #endregion

        #region Delete
        /// <summary>
        /// Mark the StaffProfileLeaveRecord Model as Deleted in DB.
        /// </summary>
        /// <param name="StaffProfileLeaveRecordId"></param>
        void DeleteStaffProfileLeaveRecord(int StaffProfileLeaveRecordId);
        /// <summary>
        /// Mark the StaffProfileLeaveRecord Model as Deleted in DB. (Async)
        /// </summary>
        /// <param name="StaffProfileLeaveRecordId"></param>
        /// <returns></returns>
        Task DeleteStaffProfileLeaveRecordAsync(int StaffProfileLeaveRecordId);
        #endregion
    }
}