// <autogenerated>
//   This file was generated using IStaffProfilePaymentDetailRepository.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>
using CBMS.Models;
using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace CBMS.Repositories.Interfaces.Roster
{
    public interface IStaffProfilePaymentDetailRepository : IRepository<StaffProfilePaymentDetailModel>,IDisposable
    {
	    /// <summary>
        /// Insert the StaffProfilePaymentDetail Model into Database
        /// </summary>
        /// <param name="StaffProfilePaymentDetail"></param>
        #region Create
        void InsertStaffProfilePaymentDetail(StaffProfilePaymentDetailModel StaffProfilePaymentDetail);
        #endregion

        #region Read
        /// <summary>
        /// Get All Active StaffProfilePaymentDetails
        /// </summary>
        /// <returns></returns>
        IQueryable<StaffProfilePaymentDetailModel> GetStaffProfilePaymentDetails();
        /// <summary>
        /// Get All Active StaffProfilePaymentDetails as Enumerable (Forced loading)
        /// </summary>
        /// <returns></returns>
        IEnumerable<StaffProfilePaymentDetailModel> GetStaffProfilePaymentDetailsAsList();
        /// <summary>
        /// Get StaffProfilePaymentDetail using its Id.
        /// </summary>
        /// <param name="StaffProfilePaymentDetailId"></param>
        /// <returns></returns>
        StaffProfilePaymentDetailModel GetStaffProfilePaymentDetailById(int StaffProfilePaymentDetailId);

        /// <summary>
        /// Get StaffProfilePaymentDetail using its Id. (Async)
        /// </summary>
        /// <param name="StaffProfilePaymentDetailId"></param>
        /// <returns></returns>
        Task<StaffProfilePaymentDetailModel> GetStaffProfilePaymentDetailByIdAsync(int StaffProfilePaymentDetailId);
        #endregion

        #region Update
        /// <summary>
        /// Update StaffProfilePaymentDetail Model.
        /// </summary>
        /// <param name="StaffProfilePaymentDetail"></param>
        void UpdateStaffProfilePaymentDetail(StaffProfilePaymentDetailModel StaffProfilePaymentDetail);
        /// <summary>
        /// Update StaffProfilePaymentDetail Model (Async)
        /// </summary>
        /// <param name="StaffProfilePaymentDetail"></param>
        /// <returns></returns>
        Task UpdateStaffProfilePaymentDetailAsync(StaffProfilePaymentDetailModel StaffProfilePaymentDetail);
        #endregion

        #region Delete
        /// <summary>
        /// Mark the StaffProfilePaymentDetail Model as Deleted in DB.
        /// </summary>
        /// <param name="StaffProfilePaymentDetailId"></param>
        void DeleteStaffProfilePaymentDetail(int StaffProfilePaymentDetailId);
        /// <summary>
        /// Mark the StaffProfilePaymentDetail Model as Deleted in DB. (Async)
        /// </summary>
        /// <param name="StaffProfilePaymentDetailId"></param>
        /// <returns></returns>
        Task DeleteStaffProfilePaymentDetailAsync(int StaffProfilePaymentDetailId);
        #endregion
    }
}