// <autogenerated>
//   This file was generated using IStaffInfoJobHistoryRepository.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>
using CBMS.Models;
using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace CBMS.Repositories.Interfaces.Roster
{
    public interface IStaffInfoJobHistoryRepository : IRepository<StaffInfoJobHistoryModel>,IDisposable
    {
	    /// <summary>
        /// Insert the StaffInfoJobHistory Model into Database
        /// </summary>
        /// <param name="StaffInfoJobHistory"></param>
        #region Create
        void InsertStaffInfoJobHistory(StaffInfoJobHistoryModel StaffInfoJobHistory);
        #endregion

        #region Read
        /// <summary>
        /// Get All Active StaffInfoJobHistorys
        /// </summary>
        /// <returns></returns>
        IQueryable<StaffInfoJobHistoryModel> GetStaffInfoJobHistories();
        /// <summary>
        /// Get All Active StaffInfoJobHistories as Enumerable (Forced loading)
        /// </summary>
        /// <returns></returns>
        IEnumerable<StaffInfoJobHistoryModel> GetStaffInfoJobHistoriesAsList();
        /// <summary>
        /// Get StaffInfoJobHistory using its Id.
        /// </summary>
        /// <param name="StaffInfoJobHistoryId"></param>
        /// <returns></returns>
        StaffInfoJobHistoryModel GetStaffInfoJobHistoryById(int StaffInfoJobHistoryId);

        /// <summary>
        /// Get StaffInfoJobHistory using its Id. (Async)
        /// </summary>
        /// <param name="StaffInfoJobHistoryId"></param>
        /// <returns></returns>
        Task<StaffInfoJobHistoryModel> GetStaffInfoJobHistoryByIdAsync(int StaffInfoJobHistoryId);
        #endregion

        #region Update
        /// <summary>
        /// Update StaffInfoJobHistory Model.
        /// </summary>
        /// <param name="StaffInfoJobHistory"></param>
        void UpdateStaffInfoJobHistory(StaffInfoJobHistoryModel StaffInfoJobHistory);
        /// <summary>
        /// Update StaffInfoJobHistory Model (Async)
        /// </summary>
        /// <param name="StaffInfoJobHistory"></param>
        /// <returns></returns>
        Task UpdateStaffInfoJobHistoryAsync(StaffInfoJobHistoryModel StaffInfoJobHistory);
        #endregion

        #region Delete
        /// <summary>
        /// Mark the StaffInfoJobHistory Model as Deleted in DB.
        /// </summary>
        /// <param name="StaffInfoJobHistoryId"></param>
        void DeleteStaffInfoJobHistory(int StaffInfoJobHistoryId);
        /// <summary>
        /// Mark the StaffInfoJobHistory Model as Deleted in DB. (Async)
        /// </summary>
        /// <param name="StaffInfoJobHistoryId"></param>
        /// <returns></returns>
        Task DeleteStaffInfoJobHistoryAsync(int StaffInfoJobHistoryId);
        #endregion
    }
}