// <autogenerated>
//   This file was generated using IStaffProfileLeaveProfileRepository.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>
using CBMS.Models;
using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace CBMS.Repositories.Interfaces.Roster
{
    public interface IStaffProfileLeaveProfileRepository : IRepository<StaffProfileLeaveProfileModel>,IDisposable
    {
	    /// <summary>
        /// Insert the StaffProfileLeaveProfile Model into Database
        /// </summary>
        /// <param name="StaffProfileLeaveProfile"></param>
        #region Create
        void InsertStaffProfileLeaveProfile(StaffProfileLeaveProfileModel StaffProfileLeaveProfile);
        #endregion

        #region Read
        /// <summary>
        /// Get All Active StaffProfileLeaveProfiles
        /// </summary>
        /// <returns></returns>
        IQueryable<StaffProfileLeaveProfileModel> GetStaffProfileLeaveProfiles();
        /// <summary>
        /// Get All Active StaffProfileLeaveProfiles as Enumerable (Forced loading)
        /// </summary>
        /// <returns></returns>
        IEnumerable<StaffProfileLeaveProfileModel> GetStaffProfileLeaveProfilesAsList();
        /// <summary>
        /// Get StaffProfileLeaveProfile using its Id.
        /// </summary>
        /// <param name="StaffProfileLeaveProfileId"></param>
        /// <returns></returns>
        StaffProfileLeaveProfileModel GetStaffProfileLeaveProfileById(int StaffProfileLeaveProfileId);

        /// <summary>
        /// Get StaffProfileLeaveProfile using its Id. (Async)
        /// </summary>
        /// <param name="StaffProfileLeaveProfileId"></param>
        /// <returns></returns>
        Task<StaffProfileLeaveProfileModel> GetStaffProfileLeaveProfileByIdAsync(int StaffProfileLeaveProfileId);
        #endregion

        #region Update
        /// <summary>
        /// Update StaffProfileLeaveProfile Model.
        /// </summary>
        /// <param name="StaffProfileLeaveProfile"></param>
        void UpdateStaffProfileLeaveProfile(StaffProfileLeaveProfileModel StaffProfileLeaveProfile);
        /// <summary>
        /// Update StaffProfileLeaveProfile Model (Async)
        /// </summary>
        /// <param name="StaffProfileLeaveProfile"></param>
        /// <returns></returns>
        Task UpdateStaffProfileLeaveProfileAsync(StaffProfileLeaveProfileModel StaffProfileLeaveProfile);
        #endregion

        #region Delete
        /// <summary>
        /// Mark the StaffProfileLeaveProfile Model as Deleted in DB.
        /// </summary>
        /// <param name="StaffProfileLeaveProfileId"></param>
        void DeleteStaffProfileLeaveProfile(int StaffProfileLeaveProfileId);
        /// <summary>
        /// Mark the StaffProfileLeaveProfile Model as Deleted in DB. (Async)
        /// </summary>
        /// <param name="StaffProfileLeaveProfileId"></param>
        /// <returns></returns>
        Task DeleteStaffProfileLeaveProfileAsync(int StaffProfileLeaveProfileId);
        #endregion
    }
}