// <autogenerated>
//   This file was generated using IStaffInfoVisaRepository.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>
using CBMS.Models;
using CBMS.Models.Roster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace CBMS.Repositories.Interfaces.Roster
{
    public interface IStaffInfoVisaRepository : IRepository<StaffInfoVisaModel>,IDisposable
    {
	    /// <summary>
        /// Insert the StaffInfoVisa Model into Database
        /// </summary>
        /// <param name="StaffInfoVisa"></param>
        #region Create
        void InsertStaffInfoVisa(StaffInfoVisaModel StaffInfoVisa);
        #endregion

        #region Read
        /// <summary>
        /// Get All Active StaffInfoVisas
        /// </summary>
        /// <returns></returns>
        IQueryable<StaffInfoVisaModel> GetStaffInfoVisas();
        /// <summary>
        /// Get All Active StaffInfoVisas as Enumerable (Forced loading)
        /// </summary>
        /// <returns></returns>
        IEnumerable<StaffInfoVisaModel> GetStaffInfoVisasAsList();
        /// <summary>
        /// Get StaffInfoVisa using its Id.
        /// </summary>
        /// <param name="StaffInfoVisaId"></param>
        /// <returns></returns>
        StaffInfoVisaModel GetStaffInfoVisaById(int StaffInfoVisaId);

        /// <summary>
        /// Get StaffInfoVisa using its Id. (Async)
        /// </summary>
        /// <param name="StaffInfoVisaId"></param>
        /// <returns></returns>
        Task<StaffInfoVisaModel> GetStaffInfoVisaByIdAsync(int StaffInfoVisaId);
        #endregion

        #region Update
        /// <summary>
        /// Update StaffInfoVisa Model.
        /// </summary>
        /// <param name="StaffInfoVisa"></param>
        void UpdateStaffInfoVisa(StaffInfoVisaModel StaffInfoVisa);
        /// <summary>
        /// Update StaffInfoVisa Model (Async)
        /// </summary>
        /// <param name="StaffInfoVisa"></param>
        /// <returns></returns>
        Task UpdateStaffInfoVisaAsync(StaffInfoVisaModel StaffInfoVisa);
        #endregion

        #region Delete
        /// <summary>
        /// Mark the StaffInfoVisa Model as Deleted in DB.
        /// </summary>
        /// <param name="StaffInfoVisaId"></param>
        void DeleteStaffInfoVisa(int StaffInfoVisaId);
        /// <summary>
        /// Mark the StaffInfoVisa Model as Deleted in DB. (Async)
        /// </summary>
        /// <param name="StaffInfoVisaId"></param>
        /// <returns></returns>
        Task DeleteStaffInfoVisaAsync(int StaffInfoVisaId);
        #endregion
    }
}